# Numpy for data science by freecodecamp
# All In One notebook


In [4]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# numpy vs list

# Proof for showing advantages of numpy over list

In [6]:
import time
import  sys

s=range(1000)
print('memeory requiremnet for list:', sys.getsizeof(1)*len(s))

memeory requiremnet for list: 28000


In [7]:
d=np.arange(1000)
print('memory requiremnet for numpy is:', d.size*d.itemsize)

memory requiremnet for numpy is: 8000


# numpy functions

# ndim: -to get diamnensions   

In [8]:
g=np.array([(1,2,3),(3,4,5),(6,7,8)])
g.ndim

2

# itemsize :- to access how much bytes occupied by each element  

In [9]:
f=np.array([1,2,3])
f.itemsize

8

# 3.to get data type use dtype

In [10]:
f.dtype

dtype('int64')

# size() :-To access total number of elements 

In [11]:
j=np.array([1,2,3])
j.size

3

In [12]:
j=np.array([(1,2,3,4),(5,6,7,8)])
j.size

8

# shape :- to get no of columns and rows

In [13]:
k=np.array([(1,2,3),(6,7,8)])
k.shape

(2, 3)

#  reshape :- for changing row size and column size

In [14]:
h=np.array([(1,2,3,4),(5,6,7,8)])
print(h)



[[1 2 3 4]
 [5 6 7 8]]


In [15]:
h=h.reshape(4,2)
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
h.shape

(4, 2)

# slicing [:] :- is mainly used to access perticular element

In [17]:
u=np.array([(1,2,3,4),(5,6,7,8)])
u

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
u[0,2]

3

In [19]:
u[0:,1:2]

array([[2],
       [6]])

# linespace():- used to print evenly spaced  sequence 

In [20]:
c=np.linspace(1,3,4)
c

array([1.        , 1.66666667, 2.33333333, 3.        ])

# max() :- maximum value in numpy array

In [21]:
x=np.array([(34,56,78),(56,67,89)])
x.max()

89

# min() :- manimum value in numpy array

In [22]:
x.min()

34

# sum() :-sum of all numbers in numpy array


In [23]:
x.sum()

380

# sum(axis=0) :-Gives  rowwise sum 

In [24]:
z=np.array([(1,4,9),(16,25,36)])
z.sum(axis=0)

array([17, 29, 45])

# sum(axis=1) :-Gives columnswise sum# 

In [25]:
z.sum(axis=1)

array([14, 77])

# sqrt() :- square root of each element in array 

In [26]:
np.sqrt(z)

array([[1., 2., 3.],
       [4., 5., 6.]])

# std() :-gives standard deviations

In [27]:
np.std(z)

12.212243401148248

# Matrix operations 


In [28]:
p=np.array([(1,2,3),(4,5,6)])
y=np.array([(4,5,1),(1,2,1)])
p+y

array([[5, 7, 4],
       [5, 7, 7]])

In [29]:
p-y

array([[-3, -3,  2],
       [ 3,  3,  5]])

In [30]:
p*y

array([[ 4, 10,  3],
       [ 4, 10,  6]])

In [31]:
p/y

array([[0.25, 0.4 , 3.  ],
       [4.  , 2.5 , 6.  ]])

# vstack((a,b)):- concat two matrices vertically

In [43]:
print(np.vstack((p,y)))

[[1 2 3]
 [4 5 6]
 [4 5 1]
 [1 2 1]]


# hstack((a,b)

In [44]:
print(np.hstack((p,y)))

[[1 2 3 4 5 1]
 [4 5 6 1 2 1]]
